/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author zhaomengzi
 */
@WebServlet(name = "confirmCreation1", urlPatterns = {"/confirmCreation1"})
public class confirmCreation1 extends HttpServlet {
    private static final String URL = "jdbc:mysql://localhost:3306/osezlessciences";
    private static final String USERNAME = "root";
    private static final String PASSWORD = "397949844";
    
    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        request.setCharacterEncoding("UTF-8");
        response.setCharacterEncoding("UTF-8");
        PrintWriter out = response.getWriter();
        ResultSet tableKeys;
        int autoGeneratedID = 0;
        
        try {
            Class.forName( "com.mysql.jdbc.Driver" );
        } catch ( ClassNotFoundException e ) {
            /* Gérer les éventuelles erreurs ici. */
        }
        
        try{
            //On se connecte au serveur
            Connection conn = DriverManager.getConnection(URL,USERNAME,PASSWORD);
            //On prépare une requête SQL
            Statement stmt = conn.createStatement();

            /**
             * enseignant
             */
            String nom_enseignant = request.getParameter("nom_enseignant");
            String prenom_enseignant = request.getParameter("prenom_enseignant");
            //vérifier si enseignant est dans BBD
            //si non, ajouter dans BDD
            ResultSet rs = stmt.executeQuery("select count(*) as nb "
                        + "from enseignant "
                            + "where upper(nomEnseignant) = upper('"+nom_enseignant+"')"
                            + "and upper(prenomEnseignant) = upper('"+prenom_enseignant+"')");
            rs.next();

            
            //nb de prénom correspondants dans BDD
            int nbEnseignant = rs.getInt("nb");
            
            //l'identifiant de l'enseignant
            int idEnseignant;
            if(nbEnseignant == 0){
                //ajouter nouveau enseignant dans BDD
                PreparedStatement editStatement = conn.prepareStatement(
                                "INSERT into Enseignant (nomEnseignant, prenomEnseignant)"
                                        + "VALUES (?,?)",Statement.RETURN_GENERATED_KEYS);
                
                editStatement.setString(1, nom_enseignant);
                editStatement.setString(2, prenom_enseignant);
//                
                editStatement.executeUpdate();
                editStatement.close();
                
                //retourner l'id d'enseignant
                rs = stmt.executeQuery("select idEnseignant from enseignant where nomEnseignant = '"+nom_enseignant+"'"
                        + "and prenomEnseignant = '"+prenom_enseignant+"'");
                rs.next();
                idEnseignant = rs.getInt(1);
                
            }else{
                rs = stmt.executeQuery("select *"
                            + "from enseignant "
                            + "where upper(nomEnseignant) = upper('"+nom_enseignant+"')"
                            + "and upper(prenomEnseignant) = upper('"+prenom_enseignant+"')");
                rs.next();
                idEnseignant = rs.getInt(1);
                
            }
            
            out.println(idEnseignant);
            /**
             * mention
             * 1 - stocker les mentions existant dans la BDD
             * 2 - obtenir leurs leur IDs en utilisant leurs nom
             */
            String nom_mention = request.getParameter("mention");
            //retourner l'id de la mention
            rs = stmt.executeQuery("select idMention from mention "
                    + "where upper(nommention) = upper('"+nom_mention+"')");
            rs.next();
            //id Mention
            int idMention = rs.getInt(1);
           
            
            /**
             * matiere
             */
            int id_matiere = 0;
            String nom_matiere = request.getParameter("nom_matiere");
            //vérifier si matiere est dans BBD
            //si non, ajouter dans BDD
            rs = stmt.executeQuery("select count(nomMatiere) as nb "
                    + "from matiere where upper(nomMatiere) = upper('"+nom_matiere+"')");
            rs.next();
            //nb de matieres correspondants dans BDD
            int nbM = rs.getInt("nb");
            
            //s'il n'y a pas
            if(nbM==0){
                
                //ajouter nouveau enseignant dans BDD
                PreparedStatement editStatement = conn.prepareStatement(
                                "INSERT into matiere(nomMatiere,idMention) VALUES (?,?)",Statement.RETURN_GENERATED_KEYS);
                
                editStatement.setString(1, nom_matiere);
                editStatement.setInt(2, idMention);
                
                
                editStatement.executeUpdate();
                editStatement.close();
                
                //retourner l'id de matiere
                rs = stmt.executeQuery("select idMatiere from matiere where nomMatiere = '"+nom_matiere+"'");
                rs.next();

                id_matiere = rs.getInt(1);
                
            }else{
                rs = stmt.executeQuery("select * "
                    + "from matiere "
                        + "where upper(nomMatiere) = upper('"+nom_matiere+"')");
                rs.next();
                
                id_matiere = rs.getInt(1);
                
            }
            out.println(id_matiere);
            

            /**
             * date
             */
            String dateCreneau = request.getParameter("date");
            Date dateC = null;
            java.sql.Date dateSql;
            try {
                dateC = new SimpleDateFormat("dd-mm-yy").parse(dateCreneau);
                
            } catch (ParseException ex) {
                Logger.getLogger(confirmCreation1.class.getName()).log(Level.SEVERE, null, ex);
            }
            dateSql = new java.sql.Date(dateC.getTime());            
            
//
            /**
             * heureDebut heureFin
             */
            String timeDebut = request.getParameter("heureDebut");
            String timeFin = request.getParameter("heureFin");
            
        
            Date date1 = null;
            Date date2 = null;
            try {
                date1 = new SimpleDateFormat("hh:mm:ss").parse(timeDebut);
                date2 = new SimpleDateFormat("hh:mm:ss").parse(timeFin);
                
            }
            catch (ParseException e) {
                request.setAttribute("time_error", "Please enter time in format HH:mm");
            } 

            java.sql.Time time1 = new Time(date1.getTime());
            java.sql.Time time2 = new Time(date2.getTime());
            
            
            /**
             * nb eleve max
             */
            String nbMax = request.getParameter("nbMax");
            int nbMaxE = Integer.parseInt(nbMax);
            
            /**
             * creneau
             */
            int id_creneau;
            
            rs = stmt.executeQuery("select max(idCreneau)  from creneau");
            rs.next();
            
            int idCreneauMax = rs.getInt(1);
            //id de nouveau matiere qu'on veut ajouter
            id_creneau = idCreneauMax + 1;
                
            //ajouter nouveau enseignant dans BDD
            PreparedStatement editStatement = conn.prepareStatement(
                        "INSERT into creneau (dateCreneau, heureDebut, heureFin, nbEleveMax,idMatiere, idEnseignant) "
                                + "VALUES (?,?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS);
            
            editStatement.setDate(1, dateSql);
            editStatement.setTime(2, time1);
            editStatement.setTime(3, time2);
            editStatement.setInt(4, nbMaxE);
            editStatement.setInt(5, id_matiere);
            editStatement.setInt(6, idEnseignant);
            editStatement.executeUpdate();
            editStatement.close();
//            
//
            
            
            /**
             * afficher des liste de créneau
             */
            //obtenir le nb de créneau
            
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Liste des créneaux</title>"); 
            out.println("<meta charset=\"utf-8\" />");
            out.println("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n" +
"		<link rel=\"stylesheet\" href=\"assets2/css/main.css\" />");
            out.println("</head>");
            
            out.println("<body class=\"homepage\">\n");
            out.println("<div id=\"page-wrapper\">");
            out.println("<div id=\"header-wrapper\">\n" +
"					<header id=\"header\" class=\"container\">\n" +
"						<!-- Logo -->\n" +
"							<div id=\"logo\">\n" +
"								<h1>Osez les sciences</h1>\n" +
"                                                        </div>\n" +
"						<!-- Nav -->\n" +
"							<nav id=\"nav\">\n" +
"								<ul>\n" +
"									<li><a href=\"gererCreneau.html\">Gérer des créneaux</a></li>\n" +
"									<li><a href=\"connexionAdmin.html\">Déconnectez vous</a></li>\n" +
"								</ul>\n" +
"							</nav>\n" +
"					</header>\n" +
"				</div>");
            out.println("</div>");
            
            out.println("<!-- Main -->" +
"				<div id=\"main-wrapper\">" +
"					<div class=\"container\">" +
                    "<div class=\"8u 12u(medium) important(medium)\">" +
"								<!-- Content -->\n" +
"                                                                <div id=\"content\" style=\"margin-left: 170px\">\n" +
"										<section class=\"last\">\n"); 
	out.println("<h1 style='margin-left:280px'>liste des créneau</h1>");
            
            out.println("<table border='2' align='center' cellpadding='15' cellspacing='10' width='150%'>");
                out.println("<tr style='border:solid;'>");
                    out.println("<th style='border:solid;' align='center'>IdCreneau</th>");
                    out.println("<th style='border:solid;'>Mention</th>");
                    out.println("<th style='border:solid;'>Date</th>");
                    out.println("<th style='border:solid;'>HeureDebut</th>");
                    out.println("<th style='border:solid;'>HeureFin</th>");
                    out.println("<th style='border:solid;'>NbEleveMax</th>");
                    out.println("<th style='border:solid;'>Matiere</th>");
                    out.println("<th style='border:solid;'>NomEnseignant</th>");
                    out.println("<th style='border:solid;'>PreomEnseignant</th>");
                out.println("</tr>");

                //obtenir les colonne de créneau
                    rs = stmt.executeQuery("SELECT * FROM  creneau c \n" +
"    INNER JOIN  matiere m ON c.IDMATIERE = m.IDMATIERE \n" +
"    inner join enseignant e on c.IDENSEIGNANT = e.IDENSEIGNANT");
                
                    
                while(rs.next()){
                    String idCreneauH = rs.getString(1);
                    int Mention = rs.getInt(10);
                    String dateCreneauH = rs.getString(2);
                    Time heureDebutH = rs.getTime(3);
                    Time heureFinH = rs.getTime(4);
                    String nbEleveMaxH = rs.getString(5);
                    String nomMatiereH = rs.getString(9);
                    String nomEnseignantH = rs.getString(12);
                    String prenomEnseignantH = rs.getString(13);

                out.println("<tr style='border:solid;' align='center'>");
                    out.println("<td style='border:solid;' align='center'>"+idCreneauH+"</td>");
                    out.println("<td style='border:solid;' align='center'>"+Mention+"</td>");
                    out.println("<td style='border:solid;' align='center'>"+dateCreneauH+"</td>");
                    out.println("<td style='border:solid;' align='center'>"+heureDebutH+"</td>");
                    out.println("<td style='border:solid;' align='center'>"+heureFinH+"</td>");
                    out.println("<td style='border:solid;' align='center'>"+nbEleveMaxH+"</td>");
                    out.println("<td style='border:solid;' align='center'>"+nomMatiereH+"</td>");
                    out.println("<td style='border:solid;' align='center'>"+nomEnseignantH+"</td>");
                    out.println("<td style='border:solid;' align='center'>"+prenomEnseignantH+"</td>");
                out.println("</tr>");
                }
            out.println("</table>");
            out.println("<form method='post' action='../OsezLesSciences/modifierCreneau' style='margin-left:260px;'>");
            out.println("<input type='submit' name='modifier' value='modifier'>");
            out.println("</form>");
            out.println("<br>");
            
            out.println("<form method='post' action='gererCreneau.html' style='margin-left:255px;'>");
            out.println("<input type='submit' name='retourner' value='retourner'>");
            out.println("</form>");
            
            out.println("</section></div></div></div></div></div>");
      
            
            out.println("</body>");
            out.println("</html>");

            rs.close();
            conn.close();
            
        }catch(SQLException ex){
            // On logge un message sur le serveur d'applicatiob
            Logger.getLogger(confirmConnexion.class.getName()).log(Level.SEVERE, null, ex);
            // On renvoie un message d'erreur au client
            response.sendError(HttpServletResponse.SC_BAD_REQUEST, ex.getMessage());        
        }finally{
            out.close();
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}